-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mar. 15 déc. 2020 à 13:16
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `users`
--

-- --------------------------------------------------------

--
-- Structure de la table `books`
--

DROP TABLE IF EXISTS `books`;
CREATE TABLE IF NOT EXISTS `books` (
  `book_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(999) COLLATE latin1_general_ci NOT NULL,
  `description` varchar(10000) COLLATE latin1_general_ci NOT NULL,
  `cover` mediumtext COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`book_id`)
) ENGINE=MyISAM AUTO_INCREMENT=56 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

--
-- Déchargement des données de la table `books`
--

INSERT INTO `books` (`book_id`, `title`, `description`, `cover`) VALUES
(10, 'WANNSEE', ' Wannsee, dans la banlieue berlinoise, le 20 janvier 1942. Une conference reunit quinze hauts fonctionnaires du IIIe Reich et de la SS autour d\'A. Eichmann et de R. Heydrich. Un huis clos documente sur la reunion au cours de laquelle a ete organisee la Shoah qui met en lumiere les conflits d\'interets et les querelles de pouvoir au sein de l\'appareil d\'Etat nazi. Avec un dossier historique. Electre 2019 ', 'https://assets.edenlivres.fr/medias/cc/529786730da2665c7f80ff88951f47f7eaa7c0.png?h=-&w=200'),
(12, 'SI C\'EST UNE FEMME', ' A partir de 1939, le camp de Ravensbruck est le theatre d\'atrocites de toutes sortes commises par les nazis sur des femmes venant de toute l\'Europe, qu\'elles soient resistantes, Tziganes, Temoins de Jehovah, Juives, malades ou prostituees. Un travail d\'enquete mene par la journaliste aupres des familles dispersees en Europe et en Israel. Electre 2020 ', 'https://couverture.numilog.com/9782702158098_W300.jpg'),
(13, 'L\'AUBE A BIRKENAU', ' Le cineaste D. Teboul retranscrit un temoignage issu de plus de quarante heures d\'entretien face camera avec S. Veil. Il retrace son enfance, sa deportation, son retour des camps, l\'antisemitisme et l\'impact de ces evenements dans ses engagements politiques. Presente aussi trois sequences de dialogues avec sa soeur Denise et deux anciens camarades de camps. Electre 2020 ', 'https://assets.edenlivres.fr/medias/0a/3748a44affc31263b7943f6567b62d0c5c139e.jpg?h=-&w=200'),
(14, 'ET SOUDAIN ILS NE RIAIENT PLUS', ' Chronique des attentats perpetres au siege social du journal satirique Charlie Hebdo et a l\'Hyper Cacher, suivie des manifestations nationales, enquete etablie d\'apres de nombreux temoignages recueillis par les quatre journalistes. Electre 2019 ', 'https://assets.edenlivres.fr/medias/2f/1a2eb217f67bbae8fda9c6513920aa23616233.jpg?h=-&w=200'),
(15, 'ATLAS DU MOYEN-ORIENT. AUX RACINES DE LA VIOLENCE', ' Une presentation des facteurs politiques et economiques responsables des nombreux conflits existant au Moyen-Orient. Les auteurs expliquent les conditions d\'une paix durable et imaginent plusieurs scenarios : disparition de l\'Irak et de la Syrie, creation d\'un Etat kurde, etc. Electre 2020 ', 'https://assets.edenlivres.fr/medias/29/6968cc28b31b5ebe364c12723025595e188767.jpg?h=-&w=200'),
(16, 'IL VOUS FAUDRA NOUS TUER', ' A 27 ans, hotesse d\'accueil dans une entreprise, Lena lit Antonin Artaud en cachette et sait que le travail est la pire excuse que se soit inventee l\'homme pour s\'empecher de vivre. Le suicide d\'un voisin agit sur elle comme une deflagration. Nous sommes en 2006, les manifestations anti-CPE enflamment la France. Lena entre au coeur de l\'action et se radicalise. Premier roman. Electre 2020 ', 'https://assets.edenlivres.fr/medias/68/dc85f1b1aa95dd5621b863120bf77dd28f9f51.jpg?h=-&w=200'),
(17, 'METRO 2033', ' En 2014, une guerre nucleaire a ravage la Terre. En 2033, quelques dizaines de Moscovites survivent dans le metro, se dotant de diverses formes de gouvernements et de croyances. Mais une menace venant de l\'exterieur plane. L\'un des survivants, Artyom, est alors charge d\'en avertir Polis, une communaute de stations qui preserve les derniers vestiges de la civilisation humaine. Electre 2020 ', 'https://www.gamannecy.com/upload/albums/202001/9791035401399_thumb.jpg'),
(51, ' MA DECO 100 % RECUP\' : 20 CREATIONS A PARTIR DE MATERIAUX ET D\'EMBALLAGES RECYCLES ', ' Vingt idees de creations a partir de materiaux et d\'objets recuperes : boites d\'oeufs, miroirs, pots de fleurs, bouteilles, ampoules, torchons, couverts en plastique, vaisselle, tabourets, etc. ©Electre 2018 ', 'https://covers.archimed.fr/Cover/VPCO/MONO/NeKcnPGWZ90n7A_SRvS1sw2/979-10-323-0341-2/MEDIUM?fallback=https%3a%2f%2fbibliotheques.paris.fr%2fui%2fskins%2fdefault%2fportal%2ffront%2fimages%2fGeneral%2fDocType%2fMONO_MEDIUM.png'),
(18, 'JEREMIAH', ' En fevrier 1892, a Montreal, des Noirs sont tortures et sauvagement assassines, rappelant les agissements du Ku Klux Klan. Charges de l\'affaire, le journaliste Joseph Laflamme et l\'inspecteur Marcel Arcand croisent la route d\'un personnage legendaire pret a tout pour mettre la main sur un precieux objet ayant appartenu a John Wilkes Booth, l\'assassin d\'Abraham Lincoln. Electre 2019 ', 'https://assets.edenlivres.fr/medias/4f/1cd13820d3ee855c8f30ac6700d524ffcbf974.jpg?h=-&w=200'),
(19, 'FRANKENSTEIN 1918', ' Un roman uchronique imaginant un monde ou la Grande Guerre a dure vingt ans. Grace aux archives du docteur Victor Frankenstein, des soldats destines a etre sacrifies sur le terrain sont crees a partir des charniers des champs de bataille. L\'entreprise est abandonnee mais le prototype Victor survit grace a Marie Curie. En 1958, il est recueilli par un jeune couple qui enquete sur cette operation. Electre 2018 ', 'https://covers.archimed.fr/Cover/VPCO/MONE/XmqdIiWvVs1n2bs2w3YlHA2/978-2-84172-871-8/MEDIUM?fallback=https%3a%2f%2fbibliotheques.paris.fr%2fui%2fskins%2fdefault%2fportal%2ffront%2fimages%2fGeneral%2fDocType%2fMONE_MEDIUM.png'),
(20, 'LA LOCOMOTIVE DES SOEURS TCHEREPANOV', ' Dix recits ayant pour point commun le motif du train. Un porteur de chapka s\'attire les foudres des femmes qui partagent son compartiment parce qu\'il sent le chocolat. La veuve d\'un mafieux voit la statue de son mari defunt la poursuivre dans le train couchette a bord duquel elle fuit avec son amant. Deux soeurs transforment la locomotive familiale en distillerie clandestine. Electre 2019 ', 'https://assets.edenlivres.fr/medias/ba/2076564b47920c7b37bd44f4d69171507fcf04.jpg?h=-&w=200'),
(21, 'LA DECONNOMIE', ' Le nouveau management n\'est pas seulement inefficace, il tue des gens. La theorie economique dominante n\'est pas simplement discutable, elle est absurde. Et les politiques economiques ne sont pas juste impuissantes a nous sortir des crises... elles nous y enfoncent ! Tout cela est a proprement parler \" deconnant \", c\'est-a-dire a la fois insense, imbecile, catastrophique et incroyable. Toutes ces folies sont clairement associees a l\'extension du pouvoir de l\'argent dans le capitalisme financiarise. Mais le pouvoir des riches n\'explique pas tout. Car les journalistes, experts, universitaires et elus qui soutiennent cette deconnomie ne sont pas tous \" au service du capital \". Des lors, rien n\'est plus troublant que l\'aisance avec laquelle une large fraction de nos \" elites \" adhere aveuglement au meme fatras d\'aneries economiques, et s\'enferme dans le deni du desastre engendre par sa propre ignorance. Diagnostiquer cet effondrement massif de l\'entendement pour lui trouver quelque antidote : tel est le but essentiel de ce livre. Un manuel d\'education citoyenne, lisible par tous, a la fois plein d\'humour et de gravite. Jacques Genereux est professeur a Sciences Po, ou il enseigne l\'economie depuis trente-cinq ans. Auteur de manuels best-sellers et de nombreux essais, il est membre de l\'Association francaise d\'economie politique et des Economistes atterres. ', 'https://assets.edenlivres.fr/medias/26/1c7d18ca8d3cf53481a2cc615aa99cc1636b4f.jpg?h=-&w=200'),
(22, 'FEMINISTES DU MONDE ARABE', ' La documentariste radio fait le portrait de jeunes feministes rencontrees en Tunisie, au Maroc, en Algerie et en Egypte en 2014. Etudiantes, ouvrieres, architectes, journalistes, agricultrices, etc., racontent leurs luttes pour le droit a la liberte sexuelle, a l\'independance, a l\'egalite juridique, economique et sociale, et au respect. Electre 2019 ', 'https://assets.edenlivres.fr/medias/76/e93a326f4896c8d5622d69a47389322ba6aee5.jpg?h=-&w=200'),
(23, 'NE NOUS LIBEREZ PAS, ON S\'EN CHARGE', ' Une sociohistoire du feminisme sous toutes ses formes, mouvements sociaux, courants de pensee, evolutions lentes et luttes sporadiques. Les historiennes questionnent la diversite des feminismes a travers le temps et leurs liens avec les luttes contre les inegalites sociales, raciales et de genre. Electre 2020 ', 'https://assets.edenlivres.fr/medias/ca/a313ee0e031acbf7984d63ed72eacf7bcd3b11.jpg?h=-&w=200'),
(24, 'LE_ZERO_ET_LE_UN.TXT', ' Le narrateur, ne dans les annees 1950, lit des romans, regarde des series et peut tomber amoureux comme tout un chacun. Mais celui-ci est une intelligence artificielle issue des travaux, tombes rapidement dans l\'oubli, des chercheurs Frank Rosenblatt et Octavia Barlov. Cette intelligence reprend vie en 2019 et livre sa biographie. Premier roman. Electre 2019\r\n ', 'https://assets.edenlivres.fr/medias/4f/2d649c88de0df2277e0077d3345d7e19ce056c.jpg?h=-&w=200'),
(25, 'LA FILLE QUI JOUAIT AVEC LE FEU', ' A 19 ans, Hannah quitte Londres pour l\'Islande afin d\'y suivre un stage dans le journal ou travaille son pere. Elle y rencontre la jeune Imogen Collins, une influenceuse Instagram. Lorsque cette derniere est accusee du meurtre du patron d\'une agence de marketing celebre, Hannah mene l\'enquete. Elle decouvre sur les reseaux sociaux la face sombre d\'Imogen. Electre 2020 ', 'https://assets.edenlivres.fr/medias/43/c01ffff368241cad798a07a41c27abc780de4e.jpg?h=-&w=200'),
(26, 'LE DIABLE S\'HABILLE EN PRADA', ' Fraichement debarquee de sa province, Andrea, journaliste debutante, vient d\'etre engagee chez Runway, un grand magazine de mode new-yorkais. Une opportunite que tout le monde lui envie... Mais Andrea est en realite propulsee un peu vite dans un univers hostile, peuple de creatures aux langues fourchues et aux silhouettes acerees. Electre 2019', 'https://assets.edenlivres.fr/medias/8c/9f5a60a244e36a66cc5ebb3a9677fc6f866ec4.jpg?h=-&w=200'),
(27, 'PAR-DELA LES SILENCES', ' Issu d\'une enquete de terrain menee en Seine-Saint-Denis, l\'ouvrage donne la parole a des migrants recemment arrives et a des familles immigrees de longue date. En se racontant, hommes et femmes sortent du silence et relatent leur travail d\'exil. Il explore la diversite des processus de metissage sociaux et culturels que vivent les habitants de quartiers populaires a forte densite immigree. Electre 2019 ', 'https://assets.edenlivres.fr/medias/63/442e3eda20ef5b6b93ed9544846c10b0b1aa3e.jpg?h=-&w=200'),
(28, 'UNE VIE (TOME 1) - WINSTON SMITH. LA BIOGRAPHIE RETROUVEE', ' En juin 1984, un taxi depose Anna Laurens devant un hotel de Saint-Veran. Le proprietaire a envoye un courrier a sa mere de la part de Winston Smith, un des pensionnaires, qui a disparu en montagne. Anna decouvre, dans sa chambre restee intacte, un manuscrit intitule Life, ecrit pour sa mere, morte quatre ans plus tot. Le manuscrit commence en 1916, au college Land priors. Electre 2020 ', 'https://assets.edenlivres.fr/medias/10/2c314b2c50e825c3b54865fb2182bf93eb06bb.jpg?h=-&w=200'),
(29, 'CE QUE LES RICHES PENSENT DES PAUVRES', ' Issu d\'une enquete sur la perception des inegalites dans les beaux quartiers de Paris, Sao Paulo et Delhi, les auteurs s\'interrogent sur la mise a distance des pauvres. Ils analysent en detail le refus de mixite et les mecanismes d\'integration des societes modernes en s\'appuyant sur l\'ouvrage du XIXe siecle de Louis Chevalier Classes laborieuses et classes dangereuses. Electre 2020 ', 'https://assets.edenlivres.fr/medias/c2/9e23a471069160c97fc0e9843d58146dcf2b37.jpg?h=-&w=200'),
(30, 'KISANGA', ' Carmin, societe miniere francaise, vient d\'annoncer son association avec un groupe chinois pour lancer dans trois mois Kisanga, une d\'exploitation miniere dans le Katanga. Olivier Martel est charge de diriger le projet sur place, mais l\'affaire attire aussi l\'attention de barbouzes et de la presse. Prix Landerneau polar 2018. Electre 2018 ', 'https://assets.edenlivres.fr/medias/c4/a5e14e1a392123e54a83f8b36e0a137de7627f.jpg?h=-&w=200'),
(31, 'LE GRAND NULLE PART', 'Trois destins paralleles de policiers, a l\'aube de l\'an 1950. C\'est la pleine epoque de la lutte contre la menace rouge, aux Etats-Unis. Electre 2020', 'https://assets.edenlivres.fr/medias/5e/47a6976b310c22920ab3abcc8fb7eb86f2e864.jpg?h=-&w=200'),
(32, '7 JOURS', ' Un tueur menace de tuer un policier par jour tant que le meurtrier de l\'avocate Hanneke Sloet ne sera pas arrete. La police du Cap, dans l\'impasse, confie l\'affaire a Benny Griessel. Mais le policier, fragilise par ses echecs personnels et sa decision d\'arreter l\'alcool, doit reprendre l\'enquete de zero. Electre 2020 ', 'https://assets.edenlivres.fr/medias/06/fbbdf35ac40dec1f9af913aafcd6a4b40375fa.jpg?h=-&w=200'),
(33, 'LOBBYTOMIE', ' Un etat des lieux de la maniere dont les firmes usent de leur pouvoir d\'influence et poussent les legislateurs a adopter des mesures en leur faveur, au detriment de la sante et de l\'environnement. Le journaliste d\'investigation decrypte les acteurs de cette propagande au service d\'interets prives, montrant le caractere antidemocratique et nefaste des lobbies. Electre 2019 ', 'https://assets.edenlivres.fr/medias/a5/1c225143af758f885217fd52424c3063c92d90.jpg?h=-&w=200'),
(34, 'WHISKEY', ' Une fresque familiale retracant l\'histoire de deux freres, Andre et Smoker. Apres une enfance passee dans le Pacifique Nord-Ouest et marquee par le divorce de leurs parents, les deux freres restent tres proches. Smoker rejoint ainsi immediatement Andre lorsqu\'il apprend que la fille de celui-ci a ete confiee par sa mere a des marginaux, installes en pleine montagne. Electre 2019 ', 'https://assets.edenlivres.fr/medias/72/3a63230962df1aab07fa92bcbf24c42de57be3.jpg?h=-&w=200'),
(35, 'L\'HISTOIRE DE L\'ART EN BD - LEONARD DE VINCI', ' La vie de Leonard de Vinci (1452-1519), peintre celebre mais egalement dessinateur, sculpteur, astronome, ingenieur, botaniste ou encore musicien. De son enfance en Toscane au manoir du Clos Luce, en passant par Venise, Florence ou Milan, l\'ouvrage presente l\'artiste emblematique de la Renaissance, grand visionnaire qui voulait tout connaitre du monde. Avec un cahier documentaire en fin d\'ouvrage. Electre 2020 ', 'https://assets.edenlivres.fr/medias/81/67c97a6e7d90bd946ffbd2d747e771c9199f04.png?h=-&w=200'),
(36, 'Ce qui n\'est pas ecrit', '\r\n Carlos emmene son fils Jorge en montagne pour un week-end entre hommes, c\'est sa mere qui l\'eleve et il le voit tres peu.\r\n\r\nIl le trouve etrange, trop rond, trop bebe pour ses quatorze ans, bref il est decu par cet ado renferme et maladroit dont il veut faire un homme, un vrai.\r\n\r\nMais des le debut de la balade c\'est Carlos qui decouvre ses limites physiques et son incapacite a communiquer avec son enfant. Le sejour s\'annonce difficile, surtout qu\'au chalet les attend la nouvelle petite amie de Carlos, qu\'il ne l\'a pas dit a son fils et qu\'elle n\'est pas un modele de discretion.\r\n\r\nCarmen restee en ville tombe sur un manuscrit laisse chez elle par Carlos, un polar scabreux et terriblement efficace ; peu a peu elle y voit de droles de ressemblances avec la realite, des premonitions macabres, des menaces a peine voilees contre elle ou contre son fils. L\'angoisse monte, les sous-entendus se multiplient.\r\nElle tente d\'appeler Jorge, mais Carlos a confisque son telephone.\r\nDesespere et humilie le garcon s\'enfuit dans la foret et disparait...\r\nOn ne lache plus ce roman parfaitement noir ou tout le monde, lecteur inclus, s\'echine a lire entre les lignes « ce qui n\'est pas ecrit », et s\'imagine le pire.\r\nThriller psychologique base sur les rancœurs et les frustrations, se deployant dans une nature inquietante sur une trame de film d\'horreur habilement construite, ce texte confirme la virtuosite stylistique et l\'inventivite narrative de son auteur. ', 'https://static2.cyberlibris.com/books_upload/300pix/9791022600637.jpg'),
(37, 'La boite a outils du Marketing digital', ' La transformation digitale dont tout le monde parle, c\'est quoi ? Le referencement naturel est-il si important qu\'on le dit ? Quelle difference entre brand content et content marketing ? Quand faut-il s\'exprimer sur les medias sociaux ? Qu\'est-ce que l\'inbound marketing ? Le growth hacking est-il une solution efficace ? Comment definir avec precision vos persona ?\r\n60 outils indispensables pour transformer en profondeur vos pratiques marketing ou tout simplement mieux les maitriser.\r\n\r\nPour s\'adapter aux nouvelles attentes des clients connectes, les fonctions marketing, communication et vente doivent profondement se reinventer. Cela peut parfois sembler complexe, mais passe le cap des acronymes barbares et des concepts nebuleux, de nouveaux horizons apparaissent. ', 'https://static2.cyberlibris.com/books_upload/300pix/9782100812691.jpg'),
(38, 'Le heros meurt a la fin', ' Voici la triste histoire de ce pauvre Herve qui, depuis sa naissance, est si malchanceux et maladroit, qu\'il ne fait qu\'accumuler les echecs et les deceptions. ', 'https://static2.cyberlibris.com/books_upload/300pix/9782898033797.jpg'),
(39, 'Electre', ' \"Un etranger (Oreste) entre escorte de trois petites filles, au moment ou, de l\'autre cote, arrivent le jardinier, en costume de fete, et les invites villageois.\r\nPREMIERE PETITE FILLE. - Ce qu\'il est beau, le jardinier !\r\nDEUXIEME PETITE FILLE. - Tu penses ! C\'est le jour de son mariage.\r\nTROISIEME PETITE FILLE. - Le voila, monsieur, votre palais d\'Agamemnon !\r\nL\'ETRANGER. - Curieuse facade !... Elle est d\'aplomb ?\r\nPREMIERE PETITE FILLE. - Non. Le cote droit n\'existe pas. On croit le voir, mais c\'est un mirage. C\'est comme le jardinier qui vient la, qui veut vous parler. Il ne vient pas. Il ne va pas pouvoir dire un mot.\r\nDEUXIEME PETITE FILLE. - Ou il va braire. Ou miauler.\"\r\nUn etranger qui n\'est autre qu\'Oreste, le fils banni d\'Agamemnon, arrive a Argos le jour ou Electre, sa soeur, va epouser le jardinier, sur l\"ordre de la reine et du regent. Electre, pleine de haine et de vengeance, cherche a connaitre la verite sur la mort de son pere... ', 'https://static2.cyberlibris.com/books_upload/300pix/9782374632902.jpg'),
(40, 'ABIGAEL', ' Novembre 1943 Accompagnee de sa tante, Abigael Mousnier se refugie chez son oncle paternel, un fermier aise etabli au pied d\'Angouleme. Son arrivee n\'enchante guere la famille qui se mefie d\'elle, car l\'orpheline de bientot 16 ans a herite des dons de sa mere: le don de guerir, et plus inquietant, le don de voir les ames errantes, de leur parler et de les aider a s\'elever vers la lumiere. Bien malgre elle, la fougueuse jeune femme se retrouve au coeur des activites de la resistance dont elle perce les secrets. Confrontee aux violences de son cousin, elle rencontre par ailleurs Adrien, un refractaire au service du travail obligatoire, dont elle tombe amoureuse. Sans doute, l\'attention que lui portera ce brave homme, tout comme l\'affection du professeur Hitier, creeront un baume sur les maux qui decoulent de ce climat accablant. Mais un mysterieux appel l\'obsede: des visions furtives d\'une femme brune, \"ni vivante ni morte\". Abigael decide de la retrouver a tout prix, protegee par un chien aux allures de loup surgi de la nuit. Est-ce vraiment par hasard qu\'elle ait emmenage en Charentes ? Jusqu\'ou cette quete la menera-t-elle ? ', 'https://static2.cyberlibris.com/books_upload/300pix/9782894317105.jpg'),
(41, 'Warren Buffett', 'Depuis pres de 50 ans, Warren Buffett applique les principes d\'investissement que vous allez decouvrir dans ce livre.\r\nNon seulement ces principes vont a l\'inverse de ce que font la plupart des investisseurs sur les marches boursiers, mais en plus ils sont d\'une desarmante simplicite !\r\nEn les appliquant avec rigueur et constance, Warren Buffett est sans conteste, et de tous les temps, devenu l\'investisseur qui a su tirer les meilleurs rendements de son portefeuille d\'actions.\r\nEn lisant Buffett, vous allez decouvrir ou redecouvrir tout l\'interet d\'une logique d\'investissement qui repose tant sur une analyse approfondie des marches et des strategies des entreprises, que sur une attention toute particuliere a la qualite des equipes de direction.\r\nL\'objectif de cette \"masterclass\" est aussi clair que la strategie d\'investissement de Warren Buffett : ameliorer considerablement la rentabilite de votre portefeuille boursier a long terme ! ', 'https://static2.cyberlibris.com/books_upload/300pix/9782840015215.jpg'),
(42, 'La Capucine', ' Si son patron ne la battait pas, si elle etait justement payee, si on ne lui comptait pas son assiette et son lit, Louise adorerait la terre sur laquelle elle travaille. Une terre incroyablement fertile, qui peut donner huit recoltes par an ! Qui exporte ses legumes jusqu\'a Londres, et meme jusqu\'en Russie.? Une terre qui n\'est qu\'a une dizaine de kilometres de Paris, sur un petit village de maraichers nomme Bobigny. Le jour ou vient la raclee de trop, Louise s\'enfuit. Direction Paris, ou vivent et travaillent sa mere Clemence, et son indefectible protectrice, Bernadette, genie de la cuisine et de la voyance reunies. Mais Louise a treize ans, et a cet age, meme si l\'on reve de liberte, encore faut-il gagner sa vie? ', 'https://static2.cyberlibris.com/books_upload/300pix/9782211151726.jpg'),
(43, 'L\'origine du capitalisme', ' Qu\'est-ce que le capitalisme? Cette question, l\'histoire la pose chaque fois que ce systeme entre en crise, etalantau grand jour ses absurdites. Pour y repondre, il faut en comprendre les origines. Voila ce que propose Ellen Meiksins Wood dans cet ouvrage initialement paru en 2009. Personne ne niera que le capitalisme a permis a l\'humanite d\'accomplir des avancees notables sur le plan materiel. Mais il est devenu aujourd\'hui manifeste que les lois du marche ne pourront faire prosperer le capital qu\'au prix d\'une deterioration des conditions de vie d\'une multitude d\'individus et d\'une degradation de l\'environnement partout dans le monde. Il importe donc plus que jamais de savoir que le capitalisme n\'est pas la consequence inevitable des echanges commerciaux et marchands que l\'on retrouve dans presque toutes les societes humaines. Le capitalisme a une histoire tres singuliere et un lieu de naissance bien precis: les campagnes anglaises du XVIIe siecle. En rappelant cette origine, essentiellement politique, l\'auteure propose une definition limpide des mecanismes et des contraintes qui font la specificite du capitalisme. ', 'https://static2.cyberlibris.com/books_upload/300pix/9782895969136.jpg'),
(44, 'De Gaulle, cinquante ans apres', ' \"Nous avons voulu cerner au plus pres la nature de l\'heritage du gaullisme, son aspect composite fait de la rencontre d\'un homme avec l\'Histoire autant qu\'avec un pays et un peuple, au point de paraitre les personnifier dans une geste inegalee. N\'a-t-on pas entendu, au debut du mouvement des Gilets jaunes, des voix reclamer un general a l\'Elysee - le general de Villiers ; l\'epoque a les ambitions qu\'elle peut -, quand, cinquante ans plus tot, d\'autres voix, plus jeunes, voulaient chasser du pouvoir un general d\'une autre trempe ? Une autre question se pose : qui aujourd\'hui porte l\'idee de rassemblement, de compagnonnage transcendant les partis, d\'un interet general peu compatible avec l\'esprit de boutique ?\" Eric Fottorino Eric Fottorino dirige cet ouvrage qui rassemble les contributions de Georges-Marc Benamou, Sudhir Hazareesingh, Vincent Martigny, Frederique Neau-Dufour, Nicolas Tenzer et Michel Winock. ', 'https://static2.cyberlibris.com/books_upload/300pix/9782815936064.jpg'),
(55, 'L\'EQUATION AFRICAINE', ' Medecin a Francfort, Kurt Krausmann mene une vie ordinaire, jusqu\'au drame familial qui va le plonger dans le desespoir. Son meilleur ami, Hans, lui propose alors de l\'emmener sur son voilier jusqu\'aux iles Comores pour une cause humanitaire. Au large des cotes somaliennes leur bateau est assailli par des pirates. Grand prix de litterature Henri-Gal 2011 pour l\'auteur. Electre 2020 ', 'https://assets.edenlivres.fr/medias/1c/e43037df3de0e08eb099de8e9056fa3888670f.jpg?h=-&w=200'),
(52, 'TON HISTOIRE, MON HISTOIRE', ' A la fin de sa vie, le poete Ted Hughes redige dans l\'urgence une sorte de confession relatant les souvenirs des sept annees passees en compagnie de sa premiere epouse, la poetesse et romanciere Sylvia Plath, qui mit fin a ses jours en 1963. L\'auteure s\'insinue dans le silence que celui-ci a longtemps garde autour de cette disparition et redonne vie a ce couple d\'ecrivains americains. Electre 2018 ', 'https://covers.archimed.fr/Cover/VPCO/MONO/btUO70kAj3j4UoVM0By4fA2/978-2-330-11496-1/MEDIUM?fallback=https%3a%2f%2fbibliotheques.paris.fr%2fui%2fskins%2fdefault%2fportal%2ffront%2fimages%2fGeneral%2fDocType%2fMONO_MEDIUM.png'),
(53, 'LUCIFER', ' Tandis que Lucas et Clara Loos passent leurs vacances sur une ile grecque, Clara fait une chute mortelle. Si la police locale conclut a un accident, tout le milieu artistique amstellodamois est au courant de la mesentente du couple et de l\'homosexualite de Lucas. Peu a peu, les doutes s\'expriment au grand jour et les hypotheses se multiplient. Roman inspire d\'un fait divers des annees 1980. ', 'https://covers.archimed.fr/Cover/VPCO/MONO/QSVeFI-MkXAnBGpNxqde7Q2/978-2-330-00062-2/MEDIUM?fallback=https%3a%2f%2fbibliotheques.paris.fr%2fui%2fskins%2fdefault%2fportal%2ffront%2fimages%2fGeneral%2fDocType%2fMONO_MEDIUM.png'),
(54, 'PRENDRE UN ENFANT PAR LA MAIN', ' A 15 ans, Max souffre d\'une maladie orpheline incurable alors qu\'une vague d\'attentats ensanglante Paris. Avec l\'aide de la jeune Sylvie, il essaie de faire naitre une idylle entre Blaise Fragonard, un editeur discret, et sa professeure de piano, Juliette Pinson, qui habitent dans le meme immeuble. Les locataires ne se doutent pas qu\'un lien les unit a une mysterieuse terroriste. Electre 2020 ', 'https://assets.edenlivres.fr/medias/2e/2edcf6857aea28bffbe1068a6a1e68057eea05.jpg?h=-&w=200'),
(49, 'Les Agronautes', ' Vous aimez la truffe ? Vous devriez alors aussi aimer les limaces sans lesquelles cet or noir ne verrait jamais le jour. Une motte de terre ? Entre les vers, \" maitres affineurs du sol \", et les champignons, dont les filaments myceliens parcourent l\'equivalent d\'un Paris-Tokyo par m2, \"c\'est le Bronx\" ! La vie grouille partout, l\'organique se combine avec le mineral, et tout s\'enrichit, tout se cree. Bien sur, \"comme dans les histoires de mafia, tout commence avec la roche-mere\". Cette observation scientifique du vivant, au sein de son environnement, montre a quel point sa preservation et sa comprehension sont essentielles. L\'agriculture moderne gere le vivant, en le contraignant (monocultures, engrais) ou en l\'eliminant (herbicides, pesticides). Le geste de l\'agronome est radicalement different ; c\'est une recherche d\'equilibres, qui tend vers un certain ideal : celui de systemes agronomiques autosuffisants, qui peuvent ainsi pratiquement se passer de toute intervention brutale... Pure agro-utopie ? Que nenni ! Agronome globe-trotter, Cedric Rabany demontre avec rigueur, style et humour, en quoi notre agriculture actuelle, accro aux engrais et aux pesticides, est obsolete ; en se basant sur des modeles existants a travers le monde – qu\'il a parcouru de long en large – l\'auteur presente enfin d\'autres voies agricoles, plus saines et perennes, qu\'il serait temps d\'explorer a grande echelle.\r\n\r\nCedric Rabany est un jeune agronome brillant, qui aime aussi le vin nu et la musique bruyante. Les Agronautes est son premier ouvrage. Globe-trotter infatigable, l\'auteur a travaille dans une trentaine de pays, du Bresil au Vietnam en passant par la Tanzanie, accumulant les experiences locales les plus diverses et autant d\'observations qui lui conferent un regard rare sur l\'agriculture mondiale, ses ecueils actuels comme ses solutions a venir. ', 'https://static2.cyberlibris.com/books_upload/300pix/9782490698158.jpg');

-- --------------------------------------------------------

--
-- Structure de la table `loginform`
--

DROP TABLE IF EXISTS `loginform`;
CREATE TABLE IF NOT EXISTS `loginform` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `User` varchar(50) NOT NULL,
  `Pass` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `loginform`
--

INSERT INTO `loginform` (`ID`, `User`, `Pass`) VALUES
(12, 'paul', 'paul'),
(18, 'admin', 'admin');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `books`
--
ALTER TABLE `books` ADD FULLTEXT KEY `description` (`description`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
